version: "3.2"
services:
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
  app:
    command: node app.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-5000}
        target: 5000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE: mongodb://mongo:27017/netguru
    links:
      - mongo
    depends_on:
      - mongo
volumes:
  mongodb:
