name: Run tests

on: [push]

env:
  PORT: 7000
  NODE_ENV: test
  JWT_SIGNING_KEY: hereforthecikeyfornetguru
  DATABASE: mongodb://localhost:27017/netguru

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        mongodb-version: [4.0, 4.2]

    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install

      - run: npm test
